sudo: false
git:
  depth: 1
language: node_js
node_js: stable
before_script:
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.com
script:
  - npm run-script pretest
  - npm run-script coverage
after_script:
  - npm install istanbul-coveralls
  - node node_modules/.bin/istanbul-coveralls
env:
  global:
    secure: Fv8nNp9Gwmcr/h8emqdgYLgfO4lV+9FSZFL4Bw+lMbi7kzRsDAsfBdCTbKT+b9P/Q/JnEphX+5mXuo34plCvjwkRWxP/8G+Y89O+VA9GfNOZIUeTBnFo3U4ClhcZdo/Lz1MpCue7gcZit1FQKN9iIJFbLFtcC1ngAGtx76wqnT0=
